### ISSUE TITLE
Output from post-receive custom hook is lost.

### ISSUE THREAD

**Issue by Aethylred** [gitlabhq/gitlab-shell#210]
I have customhooks working as per the documentation: http://doc.gitlab.com/ce/hooks/custom_hooks.html

Indeed my custom hooks all work. I have working update hook scripts and post-receive hook scripts. However the behavior of the two is different.

update hooks work as expected, output to stdout and stderr is captured and echoed to the git session that is pushing to the repository. This works when the update hook succeeds and fails.

post-receive hooks work and when the hook script fails, the output is echoed to the git session, but not when it succeeds. on a successful run of the hook all the things that it is scripted to do happen but no output is echoed to the git session.

Example output:

```
C:\Development\foo\puppet [master]> git push origin master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 299 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Checking files syntax.
remote: Checking Puppetfile
remote: Ignoring files with extensions without checks
remote: Checking files syntax done.
To git@192.168.70.11:puppet/puppet.git
   ed045e2..d95e9ae  master -> master
```

There should be some remote messages after `remote: Checking files syntax done.` and before `To git@192.168.70.11:puppet/puppet.git`

**Comment by Aethylred** [comment]
Here's the script, its an .erb template, so some changes will be required:

https://github.com/Aethylred/dynaguppy/blob/master/environments/production/modules/dynaguppy/templates/post-receive.erb

**Comment by dblessing** [comment]
What version of gitlab-shell? The first release version for custom hooks had a stdout bug but that was fixed in the subsequent release.

**Comment by dblessing** [comment]
Sorry, I am mistaken. The fix has not yet been released. This was fixed in 57c9080077524350b121dc3ade6548a4dde9a414 and will be included in the next release (hopefully on the 22nd alongside GitLab release)

**Comment by govindad** [comment]
is this fixed yet?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
