### ISSUE TITLE
Error on git push for v2.4.2

### ISSUE THREAD

**Issue by dukz** [gitlabhq/gitlab-shell#211]
Hi, 

I upgraded to latest version of GitLab CE, and checked out the latest version of gitlab-shell which kind of broke git clients trying to push their repository onto the server. 

Below is a log of the error. It seems like the change was introduced in the ff commits: 

* 6d23be22d907ad8328169d36712ea36d36107b93
* 0a6fe80686c6b14869c2f85cc223095b84f48487

I'm not familiar with the internals of this, so this is as far as I can contribute to reporting. :)

```
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 651 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: /home/git/gitlab-shell/lib/gitlab_net.rb:14:in `check_access': undefined method `join' for #<Enumerator:0x000000012ef080> (NoMethodError)
remote: 	from /home/git/gitlab-shell/lib/gitlab_access.rb:21:in `exec'
remote: 	from hooks/pre-receive:13:in `<main>'
```

**Comment by mrcuongnv** [comment]
Me too.
https://github.com/gitlabhq/gitlab-shell/commit/6d23be22d907ad8328169d36712ea36d36107b93

**Comment by dukz** [comment]
@mrcuongnv roll it back to the previous tag version (v2.4.1) which works.

Not exactly sure if there are any changes that GitLab expects from GitLab-shell v2.4.2, but so far, it's working fine for us.

**Comment by mrcuongnv** [comment]
@dukz I have also rolled back to v.2.4.1 and everything seems to be fine. Thank you!

**Comment by maxlazio** [comment]
Which version of ruby are you using?

**Comment by mrcuongnv** [comment]
Ruby v2.1.5

**Comment by maxlazio** [comment]
@mrcuongnv How did your push look like, can you list the command?

**Comment by mrcuongnv** [comment]
@maxlazio you can see the detail in my comment here https://github.com/gitlabhq/gitlab-shell/commit/6d23be22d907ad8328169d36712ea36d36107b93

**Comment by maxlazio** [comment]
@mrcuongnv Do you have any other ruby version installed on the system? The error you are receiving is typical for ruby 1.9.x. Make sure that gitlab-shell is using the correct ruby version.

**Comment by mrcuongnv** [comment]
@maxlazio Thanks! That's problem. I have a default installation of ruby in my Debian box. Just adding the path to Ruby v2 on top of `~git/.bashrc` solves my problem.

**Comment by Razer6** [comment]
Cool you figured it out. Then I'm closing this issue.

**Comment by dukz** [comment]
Gak, weird. I couldn't get RVM to use a particular version, so I had to manually set the path instead of having RVM do it for me. :(

**Comment by pulimento** [comment]
apt-get remove ruby worked for me ;) After making sure that no other app on the server was using Ruby
