### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by hknochi** [gitlabhq/gitlab-shell#224]
hey there, 

i've a problem with our gitlab-ce. 

every time a repo was pushed or pulled, another user will be blocked for about 10 seconds and get a error 

```
git clone ssh://git@example.org/example/example-component.git ssh_exchange_identification: Connection closed by remote host
git clone ssh://git@example.org/example/example-component.git fatal: Could not read from remote repository.
git clone ssh://git@example.org/example/example-component.git 
git clone ssh://git@example.org/example/example-component.git Please make sure you have the correct access rights
git clone ssh://git@example.org/example/example-component.git and the repository exists.
```

It is a dockerized gitlab-ce with a ssh-tunnel via another host. The tunnel is still working. (direct communication fails too)
- gitlab version 7.9.0
- gitlab-shell 2.6.0

may there is someone which can help 

thanks in advance

**Comment by kesin** [comment]
youcan try to increase your `MaxStartups` in your `sshd_config`, the default is `10`

**Comment by pschirch** [comment]
Hi,

I also struggling with this issue. I tried out all suggestions mentioned on http://edoceo.com/notabene/ssh-exchange-identification, including `MaxStartups` but nothing helps.

I have a repository with about 20 submodules. Executing:

```bash
git submodule foreach git fetch
```
breaks with:

```
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

If I wait some seconds, change to the submodules directory and fetch it separately all is fine.

* **Gitlab Version:** 8.0.5 (Omibus)
* **Gitlab Shell:**  2.6.5
* **OS**: Ubuntu 14.04 LTS

In addition this error message occurs randomly while working with Gitlab.

Any further advice?

**Comment by kesin** [comment]
@pschirch increase your `MaxStartups` in your `sshd_config` and reload your ssh server, in my case , the  `MaxStartups`  is `100`

**Comment by pschirch** [comment]
I tried `MaxStartups` withs `100|150|200` - but nothing helps. Which OS you are using? In Ubuntu 14.04 LTS you have to configure `MaxStartups` in this term:

```bash
MaxStartups 10:30:60
```

**Comment by kesin** [comment]
System:  Ubuntu 14.04 LTS
Software: OpenSSH 6.2
Configure: `MaxStartups 100`

**Comment by pschirch** [comment]
Unfortunately it doesnt work for me.

* **SSH Version:** OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3

**Comment by pschirch** [comment]
In this case our firewalls Brut-Force detection drops the VPN connection because too much ssh connections opened in time interval `x`. I think configuring the `MaxStartups` value is only neccessary if you have to many direct (*without any firewall*) connections from the same network and you want to enable/tweak a Brut-Force detection mode in the SSH daemon itselfs.

**Comment by dylanh724** [comment]
bump, still seekign solution in 2017 ;p

**Comment by freed00m** [comment]
@dylanh724 You are not alone, I would guess they just messed something up for a while. Hope they'll fix it soon.

**Comment by tae-jun** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/1398
Seems every gitlab users have the same issue. 😢

**Comment by stanhu** [comment]
We're investigating the issue in https://gitlab.com/gitlab-com/infrastructure/issues/2741.

**Comment by MarcosRibeiroJesus** [comment]
Same problem here! 2018
