### ISSUE TITLE
Please bump 2.6.6

### ISSUE THREAD

**Issue by bozaro** [gitlabhq/gitlab-shell#240]
For fixes:

 * #233 Custom hook environment variables
 * #234 Do not clean LANG environment variable for the git hooks when working through the SSH-protocol
 * #237 Run git-lfs-authenticate script with original command line arguments

**Comment by randx** [comment]
@bozaro can you send MR with bumping VERSION?

**Comment by bozaro** [comment]
No problem: https://gitlab.com/gitlab-org/gitlab-shell/merge_requests/22

**Comment by randx** [comment]
@bozaro thanks. I merged it and created git tag
