### ISSUE TITLE
where is v2.6.7

### ISSUE THREAD

**Issue by leecade** [gitlabhq/gitlab-shell#241]
```
GitLab Shell version >= 2.6.7 ? ... FAIL. Please update gitlab-shell to 2.6.7 from 2.6.6
```

**Comment by stanhu** [comment]
I just pushed the 2.6.7 tag, which was only available on GitLab.com.

**Comment by leecade** [comment]
I see maybe should change git upstream to gitlab.com?

**Comment by stanhu** [comment]
It's probably a good idea, since GitHub serves mostly as a mirror.

**Comment by NotSqrt** [comment]
The tag was pushed, but not the "master" branch !!

**Comment by stanhu** [comment]
Sorry, done.
