### ISSUE TITLE
Gitlab 8.6 depends on gitlab-shell v2.6.11 but none exists

### ISSUE THREAD

**Issue by fredriklindell** [gitlabhq/gitlab-shell#246]
Got a message in my Gitlab setup today saying 'update asap', so I did, following the update guide as usual. But ran into problem with gitlab-shell not having tag v2.6.11

Gitlab 8.6 depends on gitlab-shell v2.6.11 but none exists

**Comment by stanhu** [comment]
Please note the official repository is here:

https://gitlab.com/gitlab-org/gitlab-shell

I've synched this repository, so v2.6.11 is available now here, but in the future please check GitLab.com first.

**Comment by fredriklindell** [comment]
Alright @stanhu, many thanks. I was using the github repo. Should I move to https://gitlab.com/gitlab-org/gitlab-ce or stay on https://github.com/gitlabhq/gitlabhq?

**Comment by stanhu** [comment]
Use the former: GitLab.com will always have the most current version.
