### ISSUE TITLE
Missing version 4.0.3?

### ISSUE THREAD

**Issue by ahzf** [gitlabhq/gitlab-shell#251]
Hi there,

https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/8.13-to-8.14.md wants to checkout version/tag 4.0.3 but all I can see here is 4.0.2.

> ahzf@git:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
> WARNING: This version of GitLab depends on gitlab-shell 4.0.3, but you're running 4.0.2. Please update gitlab-shell.

Might this cause real problems, or not? 

Best from Jena, Germany
  Achim

**Comment by axilleas** [comment]
@stanhu can you push the `v4.0.3` tag to GitHub?

**Comment by maxlazio** [comment]
@axilleas all tags are [already pushed](https://github.com/gitlabhq/gitlab-shell/tags).

**Comment by axilleas** [comment]
Thanks @maxlazio last time I checked we were indeed missing the 4.0.3 tag. Seems fixed now.
