### ISSUE TITLE
gitlab-shell v5.0.4 tag lost

### ISSUE THREAD

**Issue by wuwx** [gitlabhq/gitlab-shell#258]
gitlabhq 9.2 needs v5.0.4

https://github.com/gitlabhq/gitlabhq/blob/9-2-stable/GITLAB_SHELL_VERSION

**Comment by stanhu** [comment]
We recommend that you use https://gitlab.com/gitlab-org/gitlab-shell as the authoritative source. The tags have been pushed here.
